# Generated by Django 5.2 on 2025-05-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('GER', 'Gerente'), ('VEN', 'Vendedor'), ('ADM', 'Administrador'), ('SUP', 'Supervisor')], max_length=50),
        ),
    ]
