# Generated by Django 5.2 on 2025-05-31 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0002_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='data_reserva',
        ),
    ]
