# Generated by Django 5.1.7 on 2025-06-16 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0004_alter_imovel_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='imobiliaria.cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='imobiliaria.imovel'),
        ),
    ]
