# Generated by Django 5.2.3 on 2025-06-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(choices=[('GER', 'Gerente'), ('ADM', 'Administrador')], max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
