# Generated by Django 5.2.3 on 2025-06-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('GER', 'Gerente'), ('ADM', 'Administrador')], max_length=50),
        ),
    ]
