# Generated by Django 5.2.3 on 2025-07-09 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '__first__'),
        ('reservas', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIAR_IMOVEL', 'Criou imóvel'), ('EDITAR_IMOVEL', 'Editou imóvel'), ('RESERVAR', 'Reservou imóvel'), ('FINALIZAR', 'Finalizou reserva'), ('CANCELAR', 'Cancelou reserva')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.imovel')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.reserva')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
