# Generated by Django 5.2.3 on 2025-07-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico_locacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoacao',
            name='acao',
            field=models.CharField(choices=[('RESERVAR', 'Reservou imóvel'), ('FINALIZAR', 'Finalizou reserva'), ('CANCELAR', 'Cancelou reserva')], max_length=20),
        ),
    ]
