# Generated by Django 5.2.3 on 2025-07-09 22:54

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AP', 'Apartamento'), ('CA', 'Casa'), ('SC', 'Sala Comercial')], max_length=2)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtyQuartos', models.IntegerField()),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos/imoveis', variations={'medium': (300, 300), 'thumb': (150, 150)})),
                ('disponibilidade', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
