# Generated by Django 5.2.3 on 2025-07-03 00:03

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='fotos/alunos', variations={'medium': (300, 300), 'thumb': (150, 150)}),
        ),
    ]
