# Generated by Django 5.2.3 on 2025-06-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='disponivel',
        ),
    ]
