# Generated by Django 5.2.3 on 2025-06-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_remove_imovel_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='estado',
            field=models.CharField(choices=[('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo')], max_length=2),
        ),
    ]
