# Generated by Django 5.2.3 on 2025-06-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_alter_imovel_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='disponibilidade',
            field=models.BooleanField(default=True),
        ),
    ]
