# Generated by Django 5.2.3 on 2025-07-09 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clientes.cliente')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='imoveis.imovel')),
            ],
            options={
                'unique_together': {('imovel', 'data_inicio', 'data_fim')},
            },
        ),
    ]
